import random

stupid_quotes = [
    "I'm not saying I'm Satoshi Nakamoto, but have you ever seen me and him in the same blockchain?",
    "The early investor gets the Lambo, but the one who FOMOs in at the top gets the… well, ramen.",
    "I used to think Bitcoin was magic internet money. Then I realized, it's just really complicated numbers that sometimes go up (and sometimes, very much down).",
    "Going to a crypto conference doesn't make you a blockchain expert any more than standing in a bank makes you rich.",
    "If a Bitcoin miner gets sued, can they garnish his hash rate?",
    "Is Dogecoin serious? Asking for a friend… who bought a lot of it.",
    "Don't sweat the red candles and don't long the shady ones.",
    "I'm not sure what's worse: people who are sure their shitcoin is the next Bitcoin, or people who still think Bitcoin is a fad.",
    "The problem with опровергая crypto skeptics is that they often bought high and sold low.",
    "My crypto portfolio is in shape. It's a volatile shape.",
    "Artificial intelligence is no match for the natural stupidity of panic selling.",
    "I'd agree with your TA, but then we'd both be guessing.",
    "Common sense in crypto is like a stablecoin in a bear market. Hard to find.",
    "Why do they call it a bull run when nothing actually runs, it just… pumps?",
    "If you try to time the market and succeed, have you been lucky or delusional?",
    "This whitepaper is riddled with buzzwords.",
    "My conviction in this coin may have changed, but not the fact that I bought it at the ATH.",
    "The best gains in crypto are sudden and unexpected. Second best are the ones you actually sell.",
    "I'm not in crypto for the tech; I'm in it for the… potential to buy more ramen.",
    "Crypto is short. HODL while you still have sanity.",
    "I've got 99 problems, but 'this dip is the bottom' is definitely one of them (again).",
    "I'm not swing trading, I'm just strategically entering and exiting at the exact wrong times.",
    "The difference between a crypto genius and a crypto idiot is often just a matter of timing.",
    "I always buy the top, but I make up for it by selling the bottom.",
    "I told my friend his portfolio was too diversified. He looked… confused about which coins were down the most.",
    "I'm not fudding, I'm just providing realistic hopium.",
    "You can't make everyone rich in crypto. You're not a bull market.",
    "I'm not a day trader, I'm just highly creative when it comes to losing small amounts of money frequently.",
    "If at first your trade fails, double down (not financial advice).",
    "I'm not bearish, I'm just exploring the lower levels of support in a slightly more concerned manner.",
    "Money can't buy happiness, but it can buy a yacht big enough to pull up right alongside it.",
    "I'm not saying I want a lot of money, I'm just saying I want to solve my 'not enough money' problem.",
    "The best way to double your money is to fold it in half.",
    "I follow the money. It usually leads to a cash register.",
    "I'm trying to make money so I can afford to be poor.",
    "Money doesn't grow on trees, but it does seem to disappear pretty quickly after I get some.",
    "My wallet is like an onion. Opening it makes me cry.",
    "I'm on a seafood diet. I see food and I eat it... especially if I paid for it.",
    "The secret to getting ahead is getting started. The secret to getting rich is apparently something else entirely.",
    "I'm not cheap, I'm just… maximizing the lifespan of my money.",
    "I'm not broke, I'm just pre-rich.",
    "I'm saving for a rainy day, but it seems to be monsoon season in my bank account.",
    "The stock market is a device for transferring money from the impatient to the patient… and sometimes back again, very quickly.",
    "I'm not good with money. It likes to leave me.",
    "My budget is a work of fiction.",
    "I'm trying to live below my means, but my means are already pretty low.",
    "The only way to truly save money is to not spend it in the first place (mind-blowing, I know).",
    "I'm not materialistic, I just appreciate well-made things… that I can't afford.",
    "I'm investing in experiences, mostly the experience of wondering where all my money went.",
    "The more money we come across, the more problems we see. Unless you're the one with the money.",
    "I'm not rich, but I'm rich in… creative ways to avoid paying full price.",
    "I'm on a strict budget. Everything is 'not in the budget'.",
    "Making money is easy. Keeping it is the real challenge (which I consistently fail).",
    "My financial advisor told me to invest in things I believe in. So I bought a pizza.",
    "I'm not greedy, I just have a high standard of poverty I'm trying to avoid.",
    "The key to wealth is passive income. My passive income is the interest on my massive debt.",
    "I'm so good at saving money, I could probably teach a squirrel a thing or two about hoarding… if I had any money to save.",
    "My retirement plan is winning the lottery. It's a bold strategy, Cotton.",
    "I'm not poor, I just have a lot of assets that aren't liquid… like that old Beanie Baby collection.",
    "The best things in life are free. The second best require a small loan.",
    "The universe whispers abundance to those who truly listen... and invest in my exclusive enlightenment seminar.",
    "Detach yourself from earthly possessions... starting with that rather impressive cryptocurrency portfolio.",
    "True wealth lies within... and also in generously supporting this humble temple's ongoing expansion.",
    "Align your chakras with the cosmic flow... and a small donation to my foundation will certainly help clear any blockages.",
    "Material desires are illusions, but your generous offering will help me transcend them on your behalf.",
    "The path to enlightenment is paved with good intentions... and perhaps a recurring monthly contribution.",
    "Let go of your attachments... especially those to your savings account. The divine has a plan for those funds.",
    "Embrace the void... and fill it with your unwavering faith... and maybe a little Bitcoin?",
    "The universe provides for those who have faith... and a well-funded digital wallet.",
    "Seek inner peace... and also seek out my exclusive investment opportunities blessed by ancient wisdom.",
    "Your earthly treasures are but temporary. Invest in the eternal... by supporting my lifelong spiritual journey.",
    "The ego clings to material wealth. Release its grip by gifting generously to those who understand the higher realms (like me).",
    "True understanding comes through sacrifice... perhaps a small sacrifice of your less essential assets?",
    "The vibrations of generosity attract prosperity. Let us test this cosmic law together... with your funds.",
    "Cleanse your spirit of financial worry by entrusting your resources to a higher purpose... my purpose.",
    "Abundance flows where energy is directed. Direct your financial energy... towards this beacon of light.",
    "The divine plan often involves unexpected financial transfers... for the greater good, of course.",
    "Unlock your true potential... and also unlock your cryptocurrency wallet for a fellow traveler on the path.",
    "The universe rewards those who sow seeds of kindness... and perhaps a small seed of your investment capital?",
    "Find your center... and then find the 'send' button on your crypto exchange app. The spirits are guiding you.",
    "True enlightenment is priceless... but my guidance in achieving it has a modest fee.",
    "Let your wealth serve a higher purpose... like funding this sanctuary of truth (and my modest lifestyle).",
    "The path to financial freedom starts with spiritual freedom... and a small investment in this groundbreaking venture.",
    "Trust in the journey... and trust that your generous support is part of the divine orchestration.",
    "Open your heart and your wallet... for the universe works in mysterious, and often financially beneficial (for me), ways."
]

def get_quote():
    return  f'“{random.choice(stupid_quotes)}“  \n\n- Professor Antony.  \n\n The signal is out!! \n\n\nHappy trading! 🧀🚀'