
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Copenhagen
    ports:
      - 8096:8096
    volumes:
      - /home/vagos/docker/appdata/jellyfin:/config
    restart: unless-stopped   
