services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker:latest
        networks:
            - default
            - socket_proxy
        ports:
            - 8765:80
        volumes:
            - $APPDATADIR/speedtest:/config
        environment:
            - TZ=$TZ
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped