services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    # environment:
      # - PASSWORD=$WG_PASSWORD
      # - WG_HOST=$PUB_IP
    volumes:
      - $APPDATADIR/wireguard/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1