services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "all"]
    networks:
      - socket_proxy
      - default
    ports:
      - "3000:3000"
    volumes:
      - $APPDATADIR/homepage:/app/config
      - $DOCKERDIR/.env:/app/config/.env
      - $DATADIR2:/data/data2:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: media.server:3000,192.168.22.144:3000,localhost,127.0.0.1

   
