services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # security_opt:
    #   - no-new-privileges:true
    # profiles: ["apps", "all"]
    networks:
      - default
      - socket_proxy
    ports:
      - "9696:9696"
      - "8191:8191"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
