services:
  # Radarr - Movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    # profiles: ["media", "arrs", "all"]
    networks:
      - socket_proxy
      - default
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR/data/media/movies:/data/movies1
      #- $DATADIR/data2/media/movies:/data/movies2
      - $DATADIR/downloads:/data/downloads 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
