services:
  # Radarr - Movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "arrs", "all"]
    networks:
      - socket_proxy
      - default
    ports:
      - "7878:7878"
    volumes:
      - $APPDATADIR/radarr:/config
      # - $DATADIR/data/media/movies:/data/movies1
      - $DATADIR2/Movies:/data/movies
      - $DATADIR/downloads:/data/downloads 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
