services:
  # Sonarr - TV Shows Management
  # Set url_base in sonarr settings if using PathPrefix
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "arrs", "all"]
    networks:
      - socket_proxy
      - default
    ports:
      - "8989:8989"
    volumes:
      - $APPDATADIR/sonar:/config
      # - $DATADIR/data/media/shows:/data/shows1
      - $DATADIR2/Tv:/data/shows
      - $DATADIR/downloads:/data/downloads 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
